name: called
run-name: ${{ github.actor }} is learning reusable workflows
on:
  workflow_run:
    workflows: [GitHub Actions Demo]
    types:
      - completed
jobs:
  check-bats-version:
    uses: ./.github/workflows/called.yml
    with:
      test-group-count: 3
