name: called
run-name: ${{ github.actor }} is learning reusable workflows
on:
  workflow_dispatch:
jobs:
  check-bats-version:
    uses: ./.github/workflows/called.yml
    with:
      test-group-count: 3
